### ISSUE TITLE
El archivo senado no tiene extensión .csv

### ISSUE THREAD

**Issue by rosgori** [infrahumano/elecciones2018#1]
Sugerencia quisquillosa:

El archivo `senado.gz` contiene un archivo llamado `senado` que no tiene extensión `.csv`. No es preocupante al principio, sólo es necesario cambiar el nombre a `senado.csv`, pero para tener compatibilidad con los tres sistemas operativos principales y que no haya problemas al abrir `senado`, es preferible que el archivo sea `.csv`.

**Comment by infrahumano** [comment]
Es un archivo `gz`, en realidad. Una vez descomprimido se obtiene un `csv`. 

De cualquier modo uniformicé los nombres.
